version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        - BUILD_ENV=production
        - GO_VER=1.23
        - VERSION=0.0.1
        - ALPINE_VER=3.20
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - DB_HOST=postgres
      - DB_USER=your_username
      - DB_PASSWORD=your_password
      - DB_NAME=your_database_name
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - adminplane


  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    networks:
      - adminpanel

networks:
  adminpanel:
