version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        - BUILD_ENV=production
        - GO_VER=1.23
        - VERSION=0.0.1
        - ALPINE_VER=3.20
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
